language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

before_script:
  - composer install --dev --prefer-source
  - phpenv rehash

script:
  - ./vendor/bin/phpunit

notifications:
  email: false
