language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

before_install:
  - composer self-update

before_script:
  - composer install --dev
  - phpenv rehash

script:
  - phpunit

notifications:
  email: false
